### ISSUE TITLE
can't connect stlink

### ISSUE THREAD

**Issue by USTHzhanglu** [RT-Thread-Studio/sdk-debugger-pyocd#18]
when i use `pyocd list`
it's show me:
`No available debug probes are connected`
how can i use it?

**Comment by eclipsesw** [comment]
use it alone  in commandline ？  usually， we use it in RT-Thread Studio， maybe you could see the command line and parameters after Studio execute commandline and print the log in Console window.

**Comment by USTHzhanglu** [comment]
maybe just support dap-link
